#define kTypeFlag "-t"
#define kTypeFlagLong "-type"
#define kTypeCenter "center"
#define kTypeLastObject "last"
#define kTypeCustom "custom"
#define kPositionFlag "-pos"
#define kPositionFlagLong "-position"
#define kLastFlag "-las"
#define kLastFlagLong "-last"
#define kAlignFlag "-a"
#define kAlignFlagLong "-align"
#define kAlignWorld "world"
#define kAlignLocal "local"
#define kAlignGimbal "gimbal "
